#!/bin/bash -

PROGRAM="${0##*/}"

if [ $# -eq 0 ]; then
  echo "$PROGRAM: create JSON arrays from bash functions"
  echo "Usage: $PROGRAM file1.sh"
  exit 1
fi

in_file="$1"

if [ ! -e "$in_file" ]; then
  echo "$in_file does not exist"
  exit 1
elif [ -d "$in_file" ]; then
  echo "$in_file is a directory"
  exit 1
fi

egrep -on '[A-Za-z0-9_]+[(]+[)]' "$in_file" >/dev/null
if [ $? -eq 1 ]; then
  echo "$in_file doesn't have functions"
  exit 1
fi

for i in $(egrep -on '[A-Za-z0-9_]+[(]+[)]' "$in_file"  | awk -F ":" '{print $1}')
do
  lineno+=( "$i" )
done

for i in $(egrep -on '[A-Za-z0-9_]+[(]+[)]' "$in_file"  | awk -F ":" '{print $2}')
do
  fname+=( "$i" )
done

for ((i=0; i<${#fname[@]}; i++))
do
   echo "{\"${in_file}\":[\"$(echo ${fname[i]}\" | tr -d '()'), ${lineno[i]}]}"
done

